### ISSUE TITLE
Adding Inferno?

### ISSUE THREAD

**Issue by trueadm** [vdom-benchmark/vdom-benchmark#12]
I'm not 100% sure how to go about adding my vdom-benchmark to the GitHub pages:

https://github.com/trueadm/vdom-benchmark-inferno

What am I missing?

**Comment by localvoid** [comment]
If you want to make it work on old IE browsers, you'll need to move repo to the vdom-benchmark group, so it will be on the same domain "http://vdom-benchmark.github.io/" (I'll add you access to this group)

To deploy on github pages:

```
git checkout --orphan gh-pages
git rm -rf .
touch README.md
git add README.md
git commit -m "Init gh-pages"
git push --set-upstream origin gh-pages
git checkout master
NODE_ENV=production gulp deploy
```
