### ISSUE TITLE
IE10-11 Can't run the tests

### ISSUE THREAD

**Issue by AlexGalays** [vdom-benchmark/vdom-benchmark#13]
Even if these browsers are rubbish, we still need to know how well these libraries run with it as it may lead to different relative results with the optimization IE's JS engine will make/not make.

BenchmarkImpl.prototype.tearDown = function() {
  this._root.remove();
};

The remove function is not available on any IE (lol). Can it be replaced with  this._root.parentNode.removeChild(this._root) instead ?

**Comment by localvoid** [comment]
Most of the implementations should work in IE. Which one is failing?

**Comment by AlexGalays** [comment]
virtual-dom

**Comment by localvoid** [comment]
https://github.com/vdom-benchmark/vdom-benchmark-virtual-dom/blob/master/web/js/main.js#L42 I hope this will fix it. Uploaded new version on gh-pages.

**Comment by AlexGalays** [comment]
Thanks that fixed it.

The results are ... Surprising.
On IE11 and when compared to Chrome, The React benchmark is 3 times slower while the virtual-dom benchmark is 25 times slower.
