### ISSUE TITLE
Add virtex to the list

### ISSUE THREAD

**Issue by ashaffer** [vdom-benchmark/vdom-benchmark#18]
I've created yet another virtual dom library and implemented your awesome vdom-benchmark.  My implementation is here:

https://github.com/ashaffer/vdom-benchmark-virtex

Is there anything I need to do to get it added?  Btw thanks for creating this, it's very useful.  I intend to implement your component benchmark as well soon.  It has helped enormously with optimization.

**Comment by localvoid** [comment]
Deploy to gh-pages `gulp deploy`, and I'll add https://ashaffer.github.io/vdom-benchmark-virtex to [config.js](https://github.com/vdom-benchmark/vdom-benchmark/blob/master/web/config.js)

**Comment by ashaffer** [comment]
Alright, it's up: http://ashaffer.github.io/vdom-benchmark-virtex/  Thanks!

**Comment by localvoid** [comment]
Done.

**Comment by ashaffer** [comment]
Sweet.  Thx.
