### ISSUE TITLE
Put riotjs to test

### ISSUE THREAD

**Issue by bitinn** [vdom-benchmark/vdom-benchmark#3]
They seem to get some bad rep from overly aggressive marketing... but if they truly have their own independent implementation of virtual dom, why not?

https://github.com/muut/riotjs

**Comment by localvoid** [comment]
It seems that the term "Virtual DOM" is used in so many different places, and it is really hard to understand what people actually mean when they refer to this term. Riot doesn't have virtual dom implementation similar to other libraries in this benchmark, so there is nothing to compare.

**Comment by bitinn** [comment]
Thanks for the answer. Admittedly I haven't used it myself (I mostly use `virtual-dom`), and now I look at it a bit more, it seems like value-diff rather than dom-diff (dom can only be changed in limited cases).

I assume all of examples here use dom-diffing? I assume the complexity of diffing algorithm depends on how many edge cases a library choose to cover?

I will close this for now.
