### ISSUE TITLE
New vdom implementation

### ISSUE THREAD

**Issue by jails** [vdom-benchmark/vdom-benchmark#7]
Hi, 
I created a virtual dom implementation and I also a [valid benchmark plugin](https://github.com/crysalead-js/vdom-benchmark-dom-layer) for your vdom-benchmark application.

Are you still accepting new implementations ?

**Comment by localvoid** [comment]
Hi, yes, I'll add it to `config.js`

**Comment by jails** [comment]
Cool thanks !

**Comment by jails** [comment]
:+1:
