### ISSUE TITLE
Add Snabbdom to the benchmarks

### ISSUE THREAD

**Issue by paldepind** [vdom-benchmark/vdom-benchmark#8]
I've implemented the benchmarks for my virtual DOM library [Snabbdom](https://github.com/paldepind/snabbdom). The implementation can be [found here](https://github.com/paldepind/vdom-benchmark-snabbdom).

Thank you a lot for having created these benchmarks. They have been really helpful in my optimizations.

**Comment by paldepind** [comment]
Thank you!

The benchmark is now available here: http://vdom-benchmark.github.io/vdom-benchmark-snabbdom/

Will you update the URL or should I do a PR?

**Comment by localvoid** [comment]
Just push updated URL, no need for PR.

**Comment by paldepind** [comment]
Splendid! This is solved now :)
